- name: Copy chocoPackages
  win_copy:
    src: chocoPackages
    dest: C:\temp
    #remote_src: True

- name: Install git
  win_chocolatey:
    name: git
    state: present

#another way is win_hotfix_module
- name: Install KB2919355
  win_chocolatey:
    name: kb2919355
    state: present
  become: true
  become_method: runas
  register: KB2919355_install

- win_reboot:
  when: KB2919355_install.changed

- name: Install dotnet4.7
  win_chocolatey:
    name: dotnet4.7
    state: present

- name: Install mssqlserver2016expressadv
  win_chocolatey:
    name: mssqlserver2016expressadv
    source: 'C:\temp\chocoPackages\.artifacts'
    state: present
  register: sqlserver_install

- win_reboot:
  when: sqlserver_install.changed

- name: Install heidisql
  win_chocolatey:
    name: heidisql
    state: present

- name: Install IIS Web-Server
  win_feature:
    name: Web-Server
    state: present
    #include_sub_features: True
    include_management_tools: True
  register: IIS_install

- win_reboot:
  when: IIS_install.reboot_required
